services:
  frontend:
    build: ./frontend
    container_name: frontend_app
    environment:
      - VITE_PROXY_TARGET=http://backend:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend_app
    ports:
      - "5000:5000"
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - MONGO_URI=${MONGO_URI}
      - CLIENT_URL=http://localhost:3000
      # SERVER_URL must match the callback URL registered in Google Cloud Console
      - SERVER_URL=http://localhost:5000
      # - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge