name: PingWatch CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push backend docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pingwatch-backend:${{ github.sha }}
      
      - name: Build and push worker docker image
        uses: docker/build-push-action@v5
        with:
          context: ./worker
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pingwatch-worker:${{ github.sha }}
      
      - name: Build and push frontend docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pingwatch-frontend:${{ github.sha }}